os: Windows Server 2012 R2

init: 
  - git config --global core.autocrlf input
    
environment:
  APIKEY:
    secure: N22dextjIWSASgrnAc8pyewvbSw0LRaER4YqeRdN8udpMS4NPqOM7drXMU/1Ck20
  
# cache:
#   - src/  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified

#install:
#  - choco sources add -name sming -source 'https://www.myget.org/F/kireevco-chocolatey/'

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - bash deploy.sh

notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/b532f6f58905ff63421c
    on_build_success: true
    on_build_failure: false
    on_build_status_changed: true
